name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@docs
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Merge code from main to docs
        run: |
          git checkout -b docs
          git merge main
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - run: |
          npm i
          npm run build
      - name: Commit and push changes
        run: |
          git config --global user.name "chuanting.xu"
          git config --global user.email "1992xct@gmail.com"
          git add -A
          git commit -m "New Build [skip ci]"
          git push
