name: Build and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - run: |
          npm i
          npm run build
      - name: Commit and push changes
        run: |
          git config --global user.name "chuanting.xu"
          git config --global user.email "1992xct@gmail.com"
          git add -A
          git commit -m "New Build [skip ci]"
          git push
